# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Benchmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=255)),
                ('min_age', models.IntegerField(null=True)),
                ('avg_age', models.IntegerField(null=True)),
                ('max_age', models.IntegerField(null=True)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('avg_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_rxd', models.IntegerField(default=0)),
                ('total_attempts', models.IntegerField(default=0)),
                ('uom', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Crawled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='The URL to the WOD page', max_length=255)),
                ('date', models.DateField()),
                ('success', models.CharField(max_length=255)),
                ('crawled_on', models.DateTimeField(auto_now_add=True, verbose_name='Crawled on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('uom', models.CharField(max_length=255)),
                ('link', models.URLField(help_text='URL to the WOD page', max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
        ),
        migrations.AddField(
            model_name='benchmark',
            name='workout',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Workout'),
        ),
    ]
