# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 18:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='date',
            field=models.DateField(default=datetime.date(2017, 6, 25)),
            preserve_default=False,
        ),
    ]
