# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_workout_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crawled',
        ),
        migrations.RenameField(
            model_name='benchmark',
            old_name='total_attempts',
            new_name='count',
        ),
        migrations.RemoveField(
            model_name='benchmark',
            name='total_rxd',
        ),
        migrations.AddField(
            model_name='benchmark',
            name='rx',
            field=models.CharField(default='Maybe', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='min_score',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='benchmark',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawl.Workout'),
        ),
    ]
