# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_benchmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='The URL to the WOD page', max_length=255)),
                ('date', models.DateField()),
                ('success', models.CharField(max_length=255)),
                ('crawled_on', models.DateTimeField(auto_now_add=True, verbose_name='Crawled on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Updated on')),
            ],
        ),
    ]
